[theme]
primaryColor = "#0066FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[layout]
initial_sidebar_state = "expanded"
wide_mode = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501